# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.12
  node: 22.11.0

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-ast
    -   id: check-yaml
    -   id: check-added-large-files
        exclude: .(png|gif|mp4)$
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-case-conflict
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    - id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.13.1'
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.6.0"
    hooks:
    -   id: djade
        args: [--target-version, "5.1"]
-   repo: https://github.com/biomejs/pre-commit
    rev: "v2.2.4"
    hooks:
    -   id: biome-check
        exclude: ^static_assets/vendor/
        additional_dependencies:
        - '@biomejs/biome@1.9.4'
